"""Comment-only history rewrite. No compiler, tests, or experiment processes."""
import difflib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
REPO = ROOT / '_worktrees/rocq-lean-import/compact-peano-importer-current'
DOCS = ROOT / '_worktrees/review/importer-submission-guide-20260908'
DOCREF = 'refs/heads/docs/cslib-patches'
BASE = 'c8db0934f0718e44a66c598360ef9c55ff7d6810'
EXTERNAL = '6b885bbd3ea4f4265ad4fdbaacd9829114b5fd1e'

# Exact comment prefixes from the topic diffs, never upstream comments.
RULES = {
    '(** Rocq normally generates a [match]': '(* Record eta lets the branch consume projections of a neutral scrutinee. *)',
    '(** A nullary unit-like constructor': '(* Registered unit eta is needed to typecheck the dependent branch-only scheme. *)',
    "(** Whether Rocq's induction-scheme generator": '(* Nested hypotheses require a registered AllForall scheme. *)',
    '(** Whether [mind] occurs anywhere': '',
    '(* Lazy declarations can change application dispatch': '(* Fresh identity distinguishes dispatch histories across Summary rollback. *)',
    '(** Atomic levels used by the translation': '(** Levels whose lower bounds must survive nested-container translation. *)',
    '(** Lean names whose translated definitions': '',
    '(* A constructor may be the first reference': '(* Derived from [entries]; rebuilt on checkpoint load. *)',
    '(** Every member points to its complete mutual block': '(* Keep complete blocks for later universe instances. *)',
    '(* Nested recursors generated by Lean are not separate': '(* Auxiliary recursors may be absent from the export; never shadow a real entry. *)',
    '(** Build the auxiliary recursive result': '(* Main and auxiliary recursors need the same fix/match computation rules. *)',
    '(* Carry canonical context IDs alongside': '',
    '(* Do not store a result whose translation crossed': '(* Lazy declarations may have invalidated this translation. *)',
    '(* Boolean primitives and their strict-comparison/decision': "(* Closed-value agreement does not preserve the source's open reduction rules. *)",
    '(* The source body is already checked.': '(* Unsupported compact equations must not reject a checked source definition. *)',
    '(* Proof-only Type records have no primitive-record eta': '(* Proof-only Type records need ordinary induction: they have no primitive eta. *)',
    "(** Persistent metadata shares the parser's expression graph.": '(* Entry metadata and parser nodes must share one expression index. *)',
    '(* Names guide future wrappers; restore': '',
    '(* The names guide future wrapper declarations; replay': '',
    '(* [import] installs live state before recording': '(* Import already installed live state; on reload, defer decoding until needed. *)',
    '(* Reclaim transient conversion closures': '(* Do not retain conversion closures or reverse indices during serialization. *)',
    '(* A temporary channel avoids retaining': "(* Avoid retaining Marshal's buffers alongside the final string. *)",
    '(* Restore eligible registrations before continuing': '',
    '(* The short tail is newest-first;': '(* [Range] is newest-first; chunks are in index order. *)',
    '(* These types describe the bytes in checkpoints': '(* Preserve the pre-chunking Marshal layout. *)',
    '(* Expression indices already form a topologically ordered DAG.': "(* Encode DAG edges as indices to avoid Marshal's object-identity table. *)",
    '(* Store only indices in an open-addressed table,': '',
    '(* Keep at most half the slots occupied,': '(* Power-of-two rounding could double this temporary allocation. *)',
    '(* Reverse indices die before the final byte string': '',
    '(** Parser representation stored before the chunked index.': '',
    '(** Encode parser edges by index. Metadata must use': '(** Use [save] for metadata roots to preserve sharing with parser expressions. *)',
    '(** Fused binary decoding exposes only': '(* Decode binary literals without an intermediate unary [nat]. *)',
    '(* Chunked parser tables changed the marshalled state': '',
    '(* Definition metadata changed the marshalled state': '',
    '(* Record the strategy as a library object so imports': '(* Persist the strategy across imports. *)',
    '(** Named Lean levels that occur directly': '(** Source levels exposed directly in the translated declaration. *)',
    '(** Full Rocq universe instance as algebraic universes': '(** Complete Rocq instance, expressed over Lean universe parameters. *)',
}


def git(*args, input=None, env=None):
    return subprocess.check_output(['git', '-C', str(REPO), *args], input=input, env=env)


def textgit(*args):
    return git(*args).decode().strip()


def comments(source):
    # Quoted strings are skipped outside comments. Nested comments are kept whole.
    i = 0
    while i < len(source):
        if source.startswith('(*', i):
            start, depth = i, 1
            i += 2
            while depth:
                if i >= len(source):
                    raise ValueError('Unterminated comment')
                if source.startswith('(*', i):
                    depth += 1
                    i += 2
                elif source.startswith('*)', i):
                    depth -= 1
                    i += 2
                else:
                    i += 1
            yield start, i
        elif source[i] == '"':
            i += 1
            while i < len(source):
                if source[i] == '\\':
                    i += 2
                elif source[i] == '"':
                    i += 1
                    break
                else:
                    i += 1
        elif source[i] == "'" and (m := re.match(r"'(?:\\(?:[0-9]{3}|x[0-9a-fA-F]{2}|o[0-7]{3}|.)|[^\\'\n])'", source[i:])):
            i += len(m.group())
        elif source[i] == '{' and (m := re.match(r'\{([a-z_]*)\|', source[i:])):
            end = source.find('|' + m.group(1) + '}', i + len(m.group()))
            if end < 0:
                i += 1
            else:
                i = end + len(m.group(1)) + 2
        else:
            i += 1


def uncomment(source):
    for start, end in reversed(list(comments(source))):
        source = source[:start] + ' ' + source[end:]
    return source


def trim(source):
    changes = []
    for start, end in comments(source):
        comment = source[start:end]
        for prefix, replacement in RULES.items():
            if comment.startswith(prefix):
                changes.append((start, end, replacement, prefix))
                break
        else:
            # This explanatory block was rewritten by #70; leave upstream's
            # different four-universe comment unchanged.
            if comment.startswith('(* The Rocq cumul definitions take four universes') and 'four algebraic universes over the Lean instance' in comment:
                changes.append((start, end, '(* ULift uses [r; s; s+1; max(r+1,s+1)]; a Type motive shifts r/s to 1/2. *)', 'ULift instance'))
    result = source
    for start, end, replacement, _ in reversed(changes):
        if not replacement:
            begin = source.rfind('\n', 0, start) + 1
            after = source.find('\n', end)
            if after < 0:
                after = len(source)
            if not source[begin:start].strip() and not source[end:after].strip():
                start, end = begin, min(len(source), after + 1)
        result = result[:start] + replacement + result[end:]
    # Only comments and their surrounding whitespace may differ.
    assert re.sub(r'\s+', '', uncomment(source)) == re.sub(r'\s+', '', uncomment(result))
    return result, [c[3] for c in changes]


def tree(revision):
    result = {}
    for item in git('ls-tree', '-r', '-z', revision).split(b'\0'):
        if item:
            metadata, name = item.split(b'\t', 1)
            mode, kind, oid = metadata.decode().split()
            result[name.decode()] = (mode, kind, oid)
    return result


def prepare():
    if (HERE / 'plan.json').exists():
        raise ValueError('A plan already exists; do not recreate it')
    refs = dict(line.split() for line in textgit('for-each-ref', '--format=%(refname) %(objectname)', 'refs/heads/submit/').splitlines())
    for name in ['pr/universe-instances', 'candidate/dependent-projections-standalone', 'integration/importer-review-stock', 'integration/importer-review-experimental', 'docs/cslib-patches']:
        refs['refs/heads/' + name] = textgit('rev-parse', name)
    checked = []
    for item in textgit('worktree', 'list', '--porcelain').split('\n\n'):
        lines = item.splitlines()
        ref = next((line[7:] for line in lines if line.startswith('branch ')), '')
        if ref in refs:
            path = lines[0][9:]
            status = subprocess.check_output(['git', '-C', path, 'status', '--porcelain', '--untracked-files=no']).decode()
            if status and not (ref == DOCREF and status == ' M PR_BODIES.md\n'):
                raise ValueError(f'Dirty target {path}: {status}')
            checked.append({'path': path, 'ref': ref})
    dirty_pr = (DOCS / 'PR_BODIES.md').read_bytes()
    (HERE / 'PR_BODIES.before.md').write_bytes(dirty_pr)
    (HERE / 'before.json').write_text(json.dumps(refs, indent=2) + '\n')
    # Keep recoverable old tips outside the branch histories being reviewed.
    commands = ['start']
    for ref, oid in refs.items():
        archive = f'refs/archive/comment-cleanup-20260908/{ref[11:]}'
        existing = subprocess.run(['git', '-C', str(REPO), 'rev-parse', '--verify', archive], capture_output=True, text=True)
        if existing.returncode == 0:
            assert existing.stdout.strip() == oid, archive
        else:
            commands.append(f'create {archive} {oid}')
    git('update-ref', '--stdin', input=('\n'.join(commands + ['prepare', 'commit']) + '\n').encode())
    nodes = textgit('rev-list', '--reverse', '--topo-order', *refs.values(), '^' + BASE, '^' + EXTERNAL).splitlines()
    doc_nodes = textgit('rev-list', '--reverse', refs[DOCREF], '^' + refs['refs/heads/integration/importer-review-experimental']).splitlines()
    nodes = [n for n in nodes if n not in doc_nodes] + doc_nodes
    mapping, changes, cache = {}, {}, {}
    with tempfile.TemporaryDirectory(prefix='git-index-', dir=HERE) as temp:
        env = {**os.environ, 'GIT_INDEX_FILE': str(Path(temp) / 'index')}
        for old in nodes:
            original_tree = tree(old)
            git('read-tree', old, env=env)
            changed = {}
            for path, (mode, kind, oid) in original_tree.items():
                if not path.startswith('src/') or not path.endswith(('.ml', '.mli', '.v')):
                    continue
                if oid not in cache:
                    source = git('cat-file', 'blob', oid).decode()
                    updated, matched = trim(source)
                    new_oid = git('hash-object', '-w', '--stdin', input=updated.encode()).decode().strip() if matched else oid
                    cache[oid] = (new_oid, matched)
                new_oid, matched = cache[oid]
                if new_oid != oid:
                    git('update-index', '--cacheinfo', mode, new_oid, path, env=env)
                    changed[path] = matched
            if old == refs[DOCREF]:
                for path in ['PR_BODIES.md', 'REVIEWING.md', 'CSLIB_PATCHES.md']:
                    source = dirty_pr.decode() if path == 'PR_BODIES.md' else git('show', old + ':' + path).decode()
                    for before, after in mapping.items():
                        source = source.replace(before, after)
                        source = re.sub(r'\b' + before[:7] + r'\b', after[:7], source)
                    oid = git('hash-object', '-w', '--stdin', input=source.encode()).decode().strip()
                    git('update-index', '--cacheinfo', '100644', oid, path, env=env)
                    changed[path] = ['current branch tips / existing local PR-body update']
            new_tree = git('write-tree', env=env).decode().strip()
            parents = textgit('show', '-s', '--format=%P', old).split()
            new_parents = [mapping.get(p, p) for p in parents]
            if new_tree == textgit('rev-parse', old + '^{tree}') and parents == new_parents:
                mapping[old] = old
                continue
            author = git('show', '-s', '--format=%an%x00%ae%x00%aI', old).decode().strip().split('\0')
            commit_env = {**env, 'GIT_AUTHOR_NAME': author[0], 'GIT_AUTHOR_EMAIL': author[1], 'GIT_AUTHOR_DATE': author[2]}
            args = ['commit-tree', new_tree]
            for parent in new_parents:
                args += ['-p', parent]
            mapping[old] = git(*args, input=git('show', '-s', '--format=%B', old), env=commit_env).decode().strip()
            changes[old] = changed
    # Neither accepted upstream work nor external #72 can match a cleanup rule.
    for base in [BASE, EXTERNAL]:
        for path, (_, kind, oid) in tree(base).items():
            if path.startswith('src/') and path.endswith(('.ml', '.mli', '.v')):
                assert trim(git('cat-file', 'blob', oid).decode())[1] == [], (base, path)
    updated_refs = {ref: mapping.get(old, old) for ref, old in refs.items()}
    sync = []
    for item in checked:
        ref, directory = item['ref'], Path(item['path'])
        old, new = refs[ref], updated_refs[ref]
        paths = textgit('diff', '--name-only', old, new).splitlines()
        for path in paths:
            before = (directory / path).read_text()
            expected = git('show', old + ':' + path).decode()
            if not (ref == DOCREF and path == 'PR_BODIES.md'):
                assert before == expected, (directory, path, 'changed during prepare')
            after = git('show', new + ':' + path).decode()
            if before == after:
                continue
            diff = ''.join(difflib.unified_diff(before.splitlines(True), after.splitlines(True)))
            hunks = re.sub(r'^@@.*$', '@@', '\n'.join(diff.split('\n')[2:]), flags=re.M)
            patch = f'*** Begin Patch\n*** Update File: {directory / path}\n{hunks}\n*** End Patch\n'
            patch_path = HERE / f'sync-{len(sync):03d}.patch'
            patch_path.write_text(patch)
            sync.append(str(patch_path))
    plan = {'before': refs, 'after': updated_refs, 'mapping': mapping, 'changes': changes, 'worktrees': checked, 'patches': sync}
    (HERE / 'plan.json').write_text(json.dumps(plan, indent=2) + '\n')
    print(json.dumps({'changed_refs': sum(refs[r] != updated_refs[r] for r in refs), 'sync_patches': len(sync), 'commits': len(mapping)}))


def finalize():
    plan = json.loads((HERE / 'plan.json').read_text())
    for item in plan['worktrees']:
        new = plan['after'][item['ref']]
        result = subprocess.run(['git', '-C', item['path'], 'diff', '--quiet', new, '--'])
        assert result.returncode == 0, item
    for ref, old in plan['before'].items():
        assert textgit('rev-parse', ref) == old, ('concurrent branch update', ref)
    for item in plan['worktrees']:
        subprocess.run(['git', '-C', item['path'], 'read-tree', plan['after'][item['ref']]], check=True)
    commands = ['start']
    for ref, old in plan['before'].items():
        new = plan['after'][ref]
        if new != old:
            commands.append(f'update {ref} {new} {old}')
    git('update-ref', '--stdin', input=('\n'.join(commands + ['prepare', 'commit']) + '\n').encode())
    print('Amended topic histories and synchronized checked-out review worktrees.')


if __name__ == '__main__':
    {'prepare': prepare, 'finalize': finalize}[sys.argv[1]]()
